### ISSUE TITLE
Lose connection to home assistant

### ISSUE THREAD

**Issue by emerysteele** [manuelmayer-dev/Macro-Deck-Home-Assistant-Plugin#3]
Seems the plugin doesn't automatically reconnect to Home Assistant if HA is restarted. Have to manually restart MacroDeck or go into plugin configure menu & click Ok to force a reconnect.

**Comment by manuelmayer-dev** [comment]
Fixed in https://github.com/manuelmayer-dev/Macro-Deck-Home-Assistant-Plugin/pull/5
